feat(refund): added method to refund a transaction
crednet/cash-sdk pull request #33
Opened 2022-07-15 22:30 UTC by cheezytony

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-07-18 12:51 UTC, dammy001 requested changes

2022-07-18 13:31 UTC, cheezytony commented on src/Models/CashWallet.php
> +<?php
Why not here?

The migration happens here, so why not have the Model here as well?

2022-07-21 11:10 UTC, dammy001 commented on src/Models/CashWallet.php
> +<?php
It doesn't mean I should add it here. I'm working with query builder not eloquent so please revert that changes

2022-07-21 11:10 UTC, dammy001 commented on src/Models/CashWallet.php
> +<?php
You can always add that to your project.

2022-07-21 11:16 UTC, cheezytony commented on src/Models/CashWallet.php
> +<?php
It makes no sense to add it to the dependent project when the defining table is here.
If you can give a reason why you prefer to work with query builder instead of eloquent, i'll concede.

We're all aware the base query builder is faster but eloquent is much better in almost every scenario where speed isn't super important.

2022-07-21 11:18 UTC, cheezytony commented on src/Models/CashWallet.php
> +<?php
I really hope this isn't you just being stubborn.

2022-07-21 11:19 UTC, dammy001 commented on src/Models/CashWallet.php
> +<?php
Everything you need about wallet is made available using the trait so this is pointless. I'll say again, create this model file in your project.

2022-07-21 11:23 UTC, cheezytony commented on src/Models/CashWallet.php
> +<?php
So you are being stubborn.

It's alright.

2022-07-21 11:24 UTC, cheezytony commented
@dammy001 why do you keep changing the base branch?

2022-07-25 07:54 UTC, dammy001 commented on src/Contracts/CPCash.php
> +    public function refundTransaction(string $walletId, string $reference): mixed;
```suggestion
    public function refundTransaction(string $walletId, string $reference);
```

2022-07-25 07:54 UTC, dammy001 commented on src/Services/CashService.php
> +    public function refundTransaction(string $walletId, string $reference): mixed
```suggestion
    public function refundTransaction(string $walletId, string $reference)
```

2022-07-25 09:57 UTC, dammy001 approved these changes

2022-07-25 09:57 UTC, merged