feature(feature-configuration):add feature confoguration middleware
crednet/cash-sdk pull request #8
Opened 2021-12-16 10:10 UTC by dharmykoya

2021-12-16 10:31 UTC, dammy001 requested changes

2021-12-16 10:31 UTC, dammy001 commented on routes/cpcash.php
> +Route::post('top-up-wallet/{walletId}', [CPCashController::class, 'walletTopUp'])->middleware(['feature-access:cash-top-up']);
I think you should move this individual middleware into the config file since the middleware is not coming from package

2021-12-16 10:41 UTC, dharmykoya commented on routes/cpcash.php
> +Route::post('top-up-wallet/{walletId}', [CPCashController::class, 'walletTopUp'])->middleware(['feature-access:cash-top-up']);
I don't understand

2021-12-25 13:40 UTC, dammy001 commented
pull from master to update your branch

2022-01-27 03:32 UTC, closed without merging